interface IContentrainSystemFields  {
  ID: string;
  createdAt: string;
  updatedAt: string;
  status: string;
}

// This file isauto-generated by script.js
export interface IAuthor extends  IContentrainSystemFields {
  fullname?: string;
  job?: string;
  photosrc?: string;
  photoalt?: string;
  description?: string;
}

// This file is auto-generated by script.js
export interface IBlog extends  IContentrainSystemFields {
  slug: string;
  content: string;
  title: string;
  description: string;
  imagesrc?: string;
  imagealt?: string;
  author?: string;
  category?: string;
}
export type IBlogFields = keyof IBlog;

// This file is auto-generated by script.js
export interface IBlogCategories extends  IContentrainSystemFields {
  name?: string;
  slug?: string;
}
// Author and Category omitted type
export interface IBlogExtended extends Omit<IBlog, "author" | "category"> {
  author?: IAuthor;
  category?: IBlogCategories;
}
// This file is auto-generated by script.js
export interface IBlogHero extends  IContentrainSystemFields {
  title?: string;
  description?: string;
  imagesrc?: string;
  imagealt?: string;
  leftbuttonlabel?: string;
  leftbuttonlink?: string;
  rightbuttonlabel?: string;
  rightbuttonlink?: string;
  backgroundimage?: string;
}

// This file is auto-generated by script.js
export interface IFooter extends  IContentrainSystemFields {
  logoalt?: string;
  logosrc?: string;
  description?: string;
  leftbottomtext?: string;
  middlebottomtext?: string;
}

// This file is auto-generated by script.js
export interface IFooterBanner extends  IContentrainSystemFields {
  title?: string;
  logosrc?: string;
  logoalt?: string;
  leftbuttonlabel?: string;
  leftbuttonlink?: string;
  rightbuttonlabel?: string;
  rightbuttonlink?: string;
  backgroundimage?: string;
}

// This file is auto-generated by script.js
export interface IHeader extends  IContentrainSystemFields {
  logosrc?: string;
  logoalt?: string;
  leftbuttonlabel?: string;
  leftbuttonlink?: string;
  rightbuttonlabel?: string;
  rightbuttonlink?: string;
}

// This file is auto-generated by script.js
export interface IHomeCollaborateTeam extends  IContentrainSystemFields {
  title?: string;
  subtitle?: string;
  description?: string;
  imagesrc?: string;
  imagealt?: string;
  buttonlabel?: string;
  buttonlink?: string;
}

// This file is auto-generated by script.js
export interface IHomeContentStructure extends  IContentrainSystemFields {
  title?: string;
  subtitle?: string;
  description?: string;
  imagealt?: string;
  imagesrc?: string;
  buttonlabel?: string;
  buttonlink?: string;
}

// This file is auto-generated by script.js
export interface IHomeFeatures extends  IContentrainSystemFields {
  icon?: string;
  title?: string;
  description?: string;
  link?: string;
  buttonlabel?: string;
  buttonlink?: string;
}

// This file is auto-generated by script.js
export interface IHomeFeaturesOverview extends  IContentrainSystemFields {
  title?: string;
  subtitle?: string;
  description?: string;
  imagesrc?: string;
  imagealt?: string;
}

// This file is auto-generated by script.js
export interface IHomeFeaturesOverviewItem extends  IContentrainSystemFields {
  title?: string;
  description?: string;
  imagesrc?: string;
  imagealt?: string;
  buttonlabel?: string;
  buttonlink?: string;
}

// This file is auto-generated by script.js
export interface IHomeHero extends  IContentrainSystemFields {
  title?: string;
  description?: string;
  imagesrc?: string;
  imagealt?: string;
  leftbuttonlabel?: string;
  leftbuttonlink?: string;
  rightbuttonlabel?: string;
  rightbuttonlink?: string;
  backgroundimage?: string;
}

// This file is auto-generated by script.js
export interface INavigationItem extends  IContentrainSystemFields {
  name?: string;
  to?: string;
}

// This file is auto-generated by script.js
export interface IResourceshero extends  IContentrainSystemFields {
  title?: string;
  subtitle?: string;
}

// This file is auto-generated by script.js
export interface IResourcesItem extends  IContentrainSystemFields {
  icon?: string;
  title?: string;
  link?: string;
  color?: string;
}

// This file is auto-generated by script.js
export interface ISocialLink extends  IContentrainSystemFields {
  name?: string;
  link?: string;
}

// This file is auto-generated by script.js
export interface IUseCase extends  IContentrainSystemFields {
  slug: string;
  content: string;
  title: string;
  description: string;
  category: string;
  imagesrc?: string;
  imagealt?: string;
  authorfullname?: string;
  authorjob?: string;
  authorphotosrc?: string;
  authorphotoalt?: string;
  authordescription?: string;
}

